### ISSUE TITLE
Implement auto publishing to PyPI

### ISSUE THREAD

**Issue by dvx76** [skodaconnect/skodaconnect#118]
- [x] #119
- [ ] Deploy to Test PyPI on all pushes to master
- [ ] Mark as pre-release when appropriate. Beta version for Test PyPI
- [ ] Validate version match between release tag and version in code

**Comment by dvx76** [comment]
Refs

- https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
- https://github.com/marketplace/actions/pypi-publish
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

**Comment by dvx76** [comment]
Publishing to test pypi:

```yaml

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
```
